from __future__ import annotations

import logging
from collections.abc import Generator
from dataclasses import dataclass, field

from src.config import Settings
from src.extraction.llm_client import LLMClientProtocol, create_llm_client
from src.retrieval.hybrid import HybridRetriever, RetrievalResult
from src.retrieval.router import QueryType

logger = logging.getLogger(__name__)

AGENT_SYSTEM = """你是一个垂直领域专家 Agent，基于知识图谱和混合检索系统来回答用户问题。

## 回答规则
1. 只基于检索到的内容回答，不要编造信息
2. 如果检索内容不足以回答问题，明确告知用户
3. 在回答末尾标注信息来源（使用的检索方式和相关片段编号）
4. 保持回答简洁、准确、有条理

## 对话历史
{history}

## 检索结果
{context}

请基于以上信息回答用户问题。"""

AGENT_USER = """{query}"""


@dataclass
class Message:
    role: str  # "user" or "assistant"
    content: str
    metadata: dict = field(default_factory=dict)


class ExpertAgent:
    def __init__(self, settings: Settings, llm: LLMClientProtocol | None = None):
        self.settings = settings
        self.llm = llm or create_llm_client(settings.llm, cache_dir=None)
        self.retriever = HybridRetriever(settings)
        self.history: list[Message] = []
        self.max_history: int = 10

    def initialize(
        self,
        chunks_path: str | None = None,
        graph_path: str | None = None,
        communities_path: str | None = None,
        use_dense: bool = False,
    ) -> None:
        chunks_path = chunks_path or str(self.settings.paths.chunks_file)
        graph_path = graph_path or str(self.settings.paths.graph_file)
        communities_path = communities_path or str(self.settings.paths.communities_file)
        self.retriever.index_from_files(chunks_path, graph_path, communities_path, use_dense)
        logger.info("Agent initialized with all retrieval indices")

    def chat(self, query: str) -> str:
        self.history.append(Message(role="user", content=query))

        retrieval_result = self.retriever.search(query)

        if retrieval_result.query_type == QueryType.GLOBAL and retrieval_result.global_answer:
            answer = self._format_global_answer(retrieval_result)
        else:
            answer = self._generate_local_answer(query, retrieval_result)

        self.history.append(
            Message(
                role="assistant",
                content=answer,
                metadata={
                    "query_type": retrieval_result.query_type.value,
                    "routing_confidence": retrieval_result.routing_confidence,
                },
            )
        )

        if len(self.history) > self.max_history * 2:
            self.history = self.history[-self.max_history * 2 :]

        return answer

    def chat_stream(self, query: str) -> Generator[str, None, None]:
        """Stream the answer token by token. Yields text chunks as they arrive."""
        self.history.append(Message(role="user", content=query))

        retrieval_result = self.retriever.search(query)
        source_note = self._build_source_note(retrieval_result)

        if retrieval_result.query_type == QueryType.GLOBAL and retrieval_result.global_answer:
            # Global answer is already fully generated by Map-Reduce; stream it character by character
            full = retrieval_result.global_answer + source_note
            yield from full
            self.history.append(
                Message(
                    role="assistant",
                    content=full,
                    metadata={
                        "query_type": retrieval_result.query_type.value,
                        "routing_confidence": retrieval_result.routing_confidence,
                    },
                )
            )
        else:
            context = self._build_context(retrieval_result)
            history_text = self._build_history()
            system = AGENT_SYSTEM.format(history=history_text, context=context)

            collected = []
            for token in self.llm.chat_stream(system, AGENT_USER.format(query=query)):
                collected.append(token)
                yield token

            yield source_note
            full_answer = "".join(collected) + source_note
            self.history.append(
                Message(
                    role="assistant",
                    content=full_answer,
                    metadata={
                        "query_type": retrieval_result.query_type.value,
                        "routing_confidence": retrieval_result.routing_confidence,
                    },
                )
            )

        if len(self.history) > self.max_history * 2:
            self.history = self.history[-self.max_history * 2 :]

    def _build_source_note(self, result: RetrievalResult) -> str:
        if result.query_type == QueryType.GLOBAL:
            return "\n\n---\n📎 检索方式: graph_global (社区摘要 Map-Reduce) | 类型: global"
        sources = {source for _, _, source in result.chunks}
        return f"\n\n---\n📎 检索方式: {', '.join(sources)} | 类型: {result.query_type.value}"

    def _generate_local_answer(self, query: str, result: RetrievalResult) -> str:
        context = self._build_context(result)
        history_text = self._build_history()

        system = AGENT_SYSTEM.format(history=history_text, context=context)
        response = self.llm.chat(system, AGENT_USER.format(query=query))

        source_note = self._build_source_note(result)
        return response + source_note

    def _format_global_answer(self, result: RetrievalResult) -> str:
        return result.global_answer + self._build_source_note(result)

    def _build_context(self, result: RetrievalResult) -> str:
        if not result.chunks:
            return "（未检索到相关内容）"
        lines = []
        for i, (chunk, score, source) in enumerate(result.chunks[:5], 1):
            lines.append(f"[片段{i}] (来源: {source}, 相关度: {score:.2f})")
            lines.append(chunk.content[:500])
            lines.append("")
        return "\n".join(lines)

    def _build_history(self) -> str:
        if not self.history:
            return "（无历史对话）"
        lines = []
        recent = self.history[-6:]
        for msg in recent:
            role = "用户" if msg.role == "user" else "助手"
            lines.append(f"{role}: {msg.content[:200]}")
        return "\n".join(lines)

    def reset(self) -> None:
        self.history.clear()
